title: "Guide MVC Purview 2026 - PME Suisse"
description: "Guide de déploiement rapide (4-6h) pour une conformité nLPD défendable en PME."
url: "https://doit4everyone.github.io"
baseurl: "/purview-mvc-pme-suisse"

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
